## Numpy 


In [2]:
import numpy as np


In [3]:
array = np.array([1,2,3])

In [4]:
array

array([1, 2, 3])

# Data Type


In [5]:
array.dtype

dtype('int32')

# Shape #
$ rows$  $columns$

In [6]:
array.shape

(3,)

# Size 
$ Number $ $of $ $Elements $

In [7]:
array.size

3

# 2D-Array

In [11]:
array = np.array([[1,2,3,4,5,6],[1,5,7,6,8,9]])

In [12]:
array.shape

(2, 6)

In [13]:
array.size

12

In [14]:
array.dtype

dtype('int32')

In [17]:
array

array([[1, 2, 3, 4, 5, 6],
       [1, 5, 7, 6, 8, 9]])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((2,5),dtype="uint8")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [30]:
array.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 5, 7],
       [6, 8, 9]])